name: Evergreen Terraform
on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 5 * * *'

jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: update dependencies
        uses: patrickjahns/dependabot-terraform-action@v1