name: Dependencies
on:
  schedule:
    - cron:  '0 5 * * 4'

jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Check Terraform Dependencies
        uses: patrickjahns/dependabot-terraform-action@v1
        with:
          github_dependency_token: ${{ secrets.DEPENDENCY_GITHUB_TOKEN }}